### ISSUE TITLE
Could not find method implementaion() for arguments

### ISSUE THREAD

**Issue by n0490b** [arbelkilani/BiColored-Progress#1]
Hi I'm getting this error 
```
Could not find method implementaion() for arguments [com.github.arbelkilani:BiColored-Progress:v1.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
````

How can I fix this? Thanks

**Comment by arbelkilani** [comment]
Hello, 
Can i get more details, Log and implementation ?

**Comment by n0490b** [comment]
Hi,

I figured it out. I was copying and pasting from the readme and `implementation` was spelt wrong which was causing a build error. I updated the readme and created a pull request. Thank you for the library its great!

**Comment by arbelkilani** [comment]
Hi, 
Thanks, for using it, here for any suggestions. 
welcome
