### ISSUE TITLE
Change Percent

### ISSUE THREAD

**Issue by lejacome** [arbelkilani/BiColored-Progress#4]
How can change percent for units metrics like Kg

**Comment by arbelkilani** [comment]
Hi, @lejacome 
A new update has been made in order to satisfy your request, 
`implementation 'com.github.arbelkilani:BiColored-Progress:v1.5'`
Please feel free to come back with questions/remarks.

**Comment by lejacome** [comment]
hey @arbelkilani 

Awesome!

Thanks!!
